name: "MTProto Proxy (mtg)"
version: "1.1.0"
slug: "mtg_proxy"
description: "Легковесный MTProto прокси для Telegram"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  debug: false
  secret: ""
  bind: "0.0.0.0:9443"
  prefer_ip: "prefer-ipv4"
  proxies: ""                # <-- добавлено
schema:
  debug: bool
  secret: str
  bind: str
  prefer_ip: "prefer-ipv4|prefer-ipv6"
  proxies: str               # <-- добавлено
ports:
  9443/tcp: 9443
