name: "MTProto Proxy"
version: "1.0.0"
slug: "mtg_proxy_test"
description: "MTProto proxy for Telegram"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
ports:
  9443/tcp: 9443
ports_description:
  9443/tcp: "MTProto Proxy Port"
options:
  debug: false
  secret: "xxxxx"
  bind_to: "0.0.0.0:9443"
  concurrency: 8192
  prefer_ip: "only-ipv4"
  auto_update: true
  tolerate_time_skewness: "5s"
  allow_fallback_on_unknown_dc: false
schema:
  debug: bool
  secret: str
  bind_to: str
  concurrency: int
  prefer_ip: str
  auto_update: bool
  tolerate_time_skewness: str
  allow_fallback_on_unknown_dc: bool
